apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sservicetypedeny
spec:
  crd:
    spec:
      names:
        kind: K8sServiceTypeDeny
      validation:
        openAPIV3Schema:
          type: object
          properties:
            deniedTypes:
              type: array
              items: { type: string }
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8sservicetypedeny

      violation[{"msg": msg}] {
        input.review.kind.kind == "Service"
        denied := {t | t := input.parameters.deniedTypes[_]}
        denied[input.review.object.spec.type]
        msg := sprintf("Service type %q is denied by policy", [input.review.object.spec.type])
      }
