apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredresources
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredResources
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8srequiredresources

      violation[{"msg": msg}] {
        input.review.kind.kind == "Deployment"
        c := input.review.object.spec.template.spec.containers[_]
        not c.resources.requests.cpu
        msg := sprintf("container %q must set resources.requests.cpu", [c.name])
      }

      violation[{"msg": msg}] {
        input.review.kind.kind == "Deployment"
        c := input.review.object.spec.template.spec.containers[_]
        not c.resources.requests.memory
        msg := sprintf("container %q must set resources.requests.memory", [c.name])
      }

      violation[{"msg": msg}] {
        input.review.kind.kind == "Deployment"
        c := input.review.object.spec.template.spec.containers[_]
        not c.resources.limits.cpu
        msg := sprintf("container %q must set resources.limits.cpu", [c.name])
      }

      violation[{"msg": msg}] {
        input.review.kind.kind == "Deployment"
        c := input.review.object.spec.template.spec.containers[_]
        not c.resources.limits.memory
        msg := sprintf("container %q must set resources.limits.memory", [c.name])
      }
