apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sdenynamespaceusage
spec:
  crd:
    spec:
      names:
        kind: K8sDenyNamespaceUsage
      validation:
        openAPIV3Schema:
          type: object
          properties:
            namespaces:
              type: array
              items: { type: string }
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8sdenynamespaceusage

      violation[{"msg": msg}] {
        input.review.kind.kind == "Deployment"
        denied[input.review.object.metadata.namespace]
        msg := sprintf("namespace %q is not allowed for workloads", [input.review.object.metadata.namespace])
      }

      denied(ns) {
        input.parameters.namespaces[_] == ns
      }
