apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8singressclasstls
spec:
  crd:
    spec:
      names:
        kind: K8sIngressClassTLS
      validation:
        openAPIV3Schema:
          type: object
          properties:
            allowedClass:
              type: string
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8singressclasstls

      violation[{"msg": msg}] {
        input.review.kind.kind == "Ingress"
        input.parameters.allowedClass != ""
        input.review.object.spec.ingressClassName != input.parameters.allowedClass
        msg := sprintf("Ingress must use class %q", [input.parameters.allowedClass])
      }

      violation[{"msg": msg}] {
        input.review.kind.kind == "Ingress"
        not has_tls(input.review.object.spec.tls)
        msg := "Ingress must enable TLS"
      }

      has_tls(tls) {
        count(tls) > 0
      }
