apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8spspseccomp
spec:
  crd:
    spec:
      names:
        kind: K8sPSPSeccomp
      validation:
        openAPIV3Schema:
          type: object
          properties:
            allowedProfiles:
              type: array
              items:
                type: string
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8spspseccomp

      violation[{"msg": msg}] {
        input.review.kind.kind == "Deployment"
        profile := input.review.object.spec.template.metadata.annotations["security.alpha.kubernetes.io/seccomp/pod"]
        not allowed(profile, input.parameters.allowedProfiles)
        msg := sprintf("seccomp profile %q not allowed; allowed: %v", [profile, input.parameters.allowedProfiles])
      }

      allowed(p, allowed_list) {
        p != ""
        allowed_list[_] == p
      }
