apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8spspnohostnetwork
spec:
  crd:
    spec:
      names:
        kind: K8sPSPNoHostNetwork
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8spspnohostnetwork

      violation[{"msg": msg}] {
        input.review.kind.kind == "Deployment"
        input.review.object.spec.template.spec.hostNetwork == true
        msg := "hostNetwork is not allowed"
      }
