apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8spspnohostpath
spec:
  crd:
    spec:
      names:
        kind: K8sPSPNoHostPath
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8spspnohostpath

      violation[{"msg": msg}] {
        input.review.kind.kind == "Deployment"
        v := input.review.object.spec.template.spec.volumes[_]
        v.hostPath
        msg := "hostPath volumes are not allowed"
      }
