apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDenyNamespaceUsage
metadata:
  name: deny-default-namespace
spec:
  match:
    kinds:
    - apiGroups:
      - apps
      kinds:
      - Deployment
  parameters:
    namespaces:
    - default
