apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPPrivilegedContainer
metadata:
  name: psp-no-privileged
spec:
  match:
    kinds:
    - apiGroups:
      - apps
      kinds:
      - Deployment
