apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPSeccomp
metadata:
  name: psp-seccomp-runtime-default
spec:
  match:
    kinds:
    - apiGroups:
      - apps
      kinds:
      - Deployment
    namespaceSelector:
      matchExpressions:
      - key: pod-security.kubernetes.io/enforce
        operator: NotIn
        values:
        - privileged
  parameters:
    allowedProfiles:
    - runtime/default
    - docker/default
