apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backstage.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ default (include "backstage.fullname" .) .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: backend
          image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}"
          imagePullPolicy: {{ .Values.images.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          env:
            - name: APP_CONFIG
              value: {{ .Values.backend.env.APP_CONFIG_PATH | quote }}
          envFrom:
            - secretRef:
                name: backstage-db
            - secretRef:
                name: backstage-app
          volumeMounts:
            - name: app-config
              mountPath: /app/config/app-config.production.yaml
              subPath: app-config.production.yaml
              readOnly: true
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      volumes:
        - name: app-config
          configMap:
            name: {{ include "backstage.fullname" . }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
