apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-apps
  namespace: flux-system
spec:
  interval: 5m
  path: ./gitops/arc/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-repo
  wait: true
  patches: []
