apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-baseline
  namespace: flux-system
spec:
  interval: 5m
  path: ./gitops/arc/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-repo
  wait: true
  patches: []
