apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-sa
  namespace: backstage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backstage-basic
  namespace: backstage
rules:
  - apiGroups: [""]
    resources: ["secrets","configmaps"]
    verbs: ["get","list","watch","create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backstage-basic
  namespace: backstage
subjects:
  - kind: ServiceAccount
    name: backstage-sa
    namespace: backstage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backstage-basic
