apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-kv
  namespace: backstage
spec:
  provider:
    azurekv:
      vaultUrl: https://${AZURE_KEY_VAULT_NAME}.vault.azure.net
      authType: WorkloadIdentity
      serviceAccountRef:
        name: backstage-sa
