apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-db-secrets
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv
    kind: SecretStore
  target:
    name: backstage-db
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: ${PG_HOST_SECRET_NAME}
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: ${PG_PORT_SECRET_NAME}
    - secretKey: POSTGRES_ADMIN_USER
      remoteRef:
        key: ${PG_ADMIN_USER_SECRET_NAME}
    - secretKey: POSTGRES_ADMIN_PASSWORD
      remoteRef:
        key: ${PG_ADMIN_PASSWORD_SECRET_NAME}
    - secretKey: POSTGRES_DB
      remoteRef:
        key: ${PG_DB_SECRET_NAME}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-app-secrets
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv
    kind: SecretStore
  target:
    name: backstage-app
    creationPolicy: Owner
  data:
    - secretKey: BACKEND_AUTH_SECRET
      remoteRef:
        key: ${BACKEND_AUTH_SECRET_NAME}
    - secretKey: MSFT_CLIENT_ID
      remoteRef:
        key: ${MSFT_CLIENT_ID_SECRET_NAME}
    - secretKey: MSFT_CLIENT_SECRET
      remoteRef:
        key: ${MSFT_CLIENT_SECRET_SECRET_NAME}
    - secretKey: MSFT_TENANT_ID
      remoteRef:
        key: ${MSFT_TENANT_ID_SECRET_NAME}
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: ${GITHUB_CLIENT_ID_SECRET_NAME}
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: ${GITHUB_CLIENT_SECRET_SECRET_NAME}
    - secretKey: AZURE_STORAGE_ACCOUNT
      remoteRef:
        key: ${AZURE_STORAGE_ACCOUNT_SECRET_NAME}
    - secretKey: AZURE_STORAGE_KEY
      remoteRef:
        key: ${AZURE_STORAGE_KEY_SECRET_NAME}
    - secretKey: TECHDOCS_CONTAINER
      remoteRef:
        key: ${TECHDOCS_CONTAINER_SECRET_NAME}
